#!/bin/bash
# SPDX-License-Identifier: MIT
#
# File:    vmconfig
# Author:  Jiří Kučera, <sanczes@gmail.com>
# Date:    2020-03-28 17:42:55 +0100
# Project: Virtual Machine Tools (vmtools)
# Brief:   Edit virtual machine's configuration.
#

set -euo pipefail

PATH=".:/usr/local/share/vmtools:/usr/share/vmtools${PATH:+:}${PATH}" \
. vmtools.sh >/dev/null 2>&1 || {
  echo "I can't see vmtools.sh. Are vmtools installed?" >&2
  exit 1
}

clishe_init

clishe_defopt VMNAME "a name of virtual machine"
clishe_defopt --dry-run -- "" DRY_RUN <<__HELP__
only print what should be done, do not perform anything
__HELP__
clishe_defopt --help -h -? -- "print this screen and exit" help usage

function usage() {
  cat <<-__USAGE__
	Edit virtual machine's configuration.

	Usage: ${clishe_scriptname} VMNAME [--dry-run | --help -h -?]
	where

	${clishe_helplines}

	Open VMNAME's configuration for editing. An editor to be used for
	editing is read from VMTOOLS_EDITOR or EDITOR variable (default editor
	is \`vi\`).
	__USAGE__
  exit 0
}

clishe_process_options "$@"

DRY_RUN="${DRY_RUN:-}" vmtools_edit_config "${VMNAME}"
