#!/bin/bash
#
# File:    ./vmkill
# Author:  Jiří Kučera <sanczes AT gmail.com>
# Date:    2020-03-30 01:25:58 +0200
# Project: Virtual Machine Tools (vmtools)
# Brief:   Send a signal to virtual machine
#
# SPDX-License-Identifier: MIT
#

set -euo pipefail

function __path() {
  echo -n "${HOME}/.local/share/$1"
  echo -n ":/usr/local/share/$1"
  echo -n ":/usr/share/$1"
  echo -n "${PATH:+:}${PATH}"
}

# shellcheck source=~/.local/share/clishe/clishe.sh
PATH="$(__path "clishe")" \
. clishe.sh >/dev/null 2>&1 || {
  echo "clishe library is not installed!" >&2
  exit 1
}

PATH=".:$(__path "vmtools")" \
. vmtools.sh >/dev/null 2>&1 || {
  echo "I can't see vmtools.sh. Are vmtools installed?" >&2
  exit 1
}

clishe_init

clishe_defopt VMNAME "a name of virtual machine"
clishe_defopt SIGSPEC "" <<__HELP__
a signal specification (name or number); syntax is same as in kill command
except starting dash, so write 9, SIGTERM instead of -9, -SIGTERM
__HELP__
clishe_defopt --dry-run -- "" DRY_RUN <<__HELP__
only print what should be done, do not perform anything
__HELP__
clishe_defopt --help -h -? -- "print this screen and exit" help usage

function usage() {
  local _synopsis="VMNAME SIGSPEC [--dry-run] [--help] [-h?]"
  cat <<-__USAGE__
	Send a signal to virtual machine.

	Usage: ${clishe_scriptname} ${_synopsis}
	where

	${clishe_helplines}

	Send a signal to the qemu process that runs VMNAME virtual machine.
	__USAGE__
  exit 0
}

clishe_process_options "$@"

DRY_RUN="${DRY_RUN:-}" vmtools_vmkill "${VMNAME}" "${SIGSPEC}"
