#!/bin/bash
#
# File:    ./vmpkg
# Author:  Jiří Kučera <sanczes AT gmail.com>
# Date:    2022-08-08 20:28:06 +0200
# Project: Virtual Machine Tools (vmtools)
# Brief:   Manage VM's packages
#
# SPDX-License-Identifier: MIT
#

set -euo pipefail

# shellcheck source=/usr/local/share/clishe/clishe.sh
PATH="/usr/local/share/clishe:/usr/share/clishe${PATH:+:}${PATH}" \
. clishe.sh >/dev/null 2>&1 || {
  echo "clishe library is not installed!" >&2
  exit 1
}

PATH=".:/usr/local/share/vmtools:/usr/share/vmtools${PATH:+:}${PATH}" \
. vmtools.sh >/dev/null 2>&1 || {
  echo "I can't see vmtools.sh. Are vmtools installed?" >&2
  exit 1
}

PATH=".:/usr/local/share/vmtools:/usr/share/vmtools${PATH:+:}${PATH}" \
. pkgman.sh >/dev/null 2>&1 || {
  echo "I can't see pkgman.sh. Are vmtools installed?" >&2
  exit 1
}

clishe_init

clishe_defopt VMNAME "a name of virtual machine"
clishe_defopt ACTION "" <<__HELP__
an action to be performed, one of

  install
    install packages

  refresh
    first remove and then install packages

  remove
    remove packages
__HELP__
clishe_defopt --dry-run -- "" DRY_RUN <<__HELP__
only print what should be done, do not perform anything
__HELP__
clishe_defopt --help -h -? -- "print this screen and exit" help usage
clishe_defopt "@PKG ..." "a list of packages"

function usage() {
  local _synopsis=(
    'VMNAME' 'ACTION' '[--dry-run]' '[--help]' '[-h?]' '[PKG [...]]'
  )

  cat <<-__USAGE__
	Manage packages on the virtual machine.

	Usage: ${clishe_scriptname} ${_synopsis[*]}
	where

	${clishe_helplines}
	__USAGE__
  exit 0
}

clishe_process_options "$@"

DRY_RUN="${DRY_RUN:-}" \
manage_packages "${VMNAME}" "${ACTION}" "${clishe_tailopts[@]}"
