#!/bin/bash
#
# File:    ./vmtools-images
# Author:  Jiří Kučera <sanczes AT gmail.com>
# Date:    2022-08-01 13:26:57 +0200
# Project: Virtual Machine Tools (vmtools)
# Brief:   List virtual machine images
#
# SPDX-License-Identifier: MIT
#

set -euo pipefail

# shellcheck source=/usr/local/share/clishe/clishe.sh
PATH="/usr/local/share/clishe:/usr/share/clishe${PATH:+:}${PATH}" \
. clishe.sh >/dev/null 2>&1 || {
  echo "clishe library is not installed!" >&2
  exit 1
}

PATH=".:/usr/local/share/vmtools:/usr/share/vmtools${PATH:+:}${PATH}" \
. vmtools.sh >/dev/null 2>&1 || {
  echo "I can't see vmtools.sh. Are vmtools installed?" >&2
  exit 1
}

clishe_init

clishe_defopt --dry-run -- "" DRY_RUN <<__HELP__
only print what should be done, do not perform anything
__HELP__
clishe_defopt --help -h -? -- "print this screen and exit" help usage

function usage() {
  cat <<-__USAGE__
	List virtual machine images.

	Usage: ${clishe_scriptname} [--dry-run] [--help] [-h?]
	where

	${clishe_helplines}

	Prints a list of images. For each image, it prints its name, type
	(as determined by \`file\`), modification time, user/group, and size.
	The format of each row can be set via VMTOOLS_IMAGE_LIST_FORMAT. The
	format should be understandable by \`printf\`, default format is
	"${__image_list_format}". Images listed are those matching the
	regular expression in VMTOOLS_IMAGE_RE, default is "\\.qcow2\$".
	__USAGE__
  exit 0
}

clishe_process_options "$@"

DRY_RUN="${DRY_RUN:-}" vmtools_list_images
