#!/bin/bash
#
# File:    ./vmtools-vms
# Author:  Jiří Kučera <sanczes AT gmail.com>
# Date:    2022-08-01 19:59:30 +0200
# Project: Virtual Machine Tools (vmtools)
# Brief:   List running VMs
#
# SPDX-License-Identifier: MIT
#

set -euo pipefail

# shellcheck source=/usr/local/share/clishe/clishe.sh
PATH="/usr/local/share/clishe:/usr/share/clishe${PATH:+:}${PATH}" \
. clishe.sh >/dev/null 2>&1 || {
  echo "clishe library is not installed!" >&2
  exit 1
}

PATH=".:/usr/local/share/vmtools:/usr/share/vmtools${PATH:+:}${PATH}" \
. vmtools.sh >/dev/null 2>&1 || {
  echo "I can't see vmtools.sh. Are vmtools installed?" >&2
  exit 1
}

clishe_init

clishe_defopt --dry-run -- "" DRY_RUN <<__HELP__
only print what should be done, do not perform anything
__HELP__
clishe_defopt --help -h -? -- "print this screen and exit" help usage

function usage() {
  cat <<-__USAGE__
	List running VMs.

	Usage: ${clishe_scriptname} [--dry-run] [--help] [-h?]
	where

	${clishe_helplines}

	List running virtual machines, one machine per line, each line
	containing the name of the virtual machine, process ID, socket, and
	path to the used image file. The line format can be changed via
	VMTOOLS_VM_LIST_FORMAT, following the \`printf\` format. By default
	"${__vm_list_format}" is used. The running virtual machines are those
	their process matches VMTOOLS_QEMU_PROC_RE regular expression, default
	is "qemu". As image files are considered those files their name matches
	VMTOOLS_IMAGE_RE regular expression, default is "\\.qcow2\$". If the
	path to the used image is inside parentheses, it means that the image
	file has been deleted.
	__USAGE__
  exit 0
}

clishe_process_options "$@"

DRY_RUN="${DRY_RUN:-}" vmtools_vms
