#!/bin/bash
#
# File:    ./vmtools-config
# Author:  Jiří Kučera <sanczes AT gmail.com>
# Date:    2020-03-28 17:05:32 +0100
# Project: Virtual Machine Tools (vmtools)
# Brief:   Edit vmtools configuration
#
# SPDX-License-Identifier: MIT
#

set -euo pipefail

function __path() {
  echo -n "${HOME}/.local/share/$1"
  echo -n ":/usr/local/share/$1"
  echo -n ":/usr/share/$1"
  echo -n "${PATH:+:}${PATH}"
}

# shellcheck source=~/.local/share/clishe/clishe.sh
PATH="$(__path "clishe")" \
. clishe.sh >/dev/null 2>&1 || {
  echo "clishe library is not installed!" >&2
  exit 1
}

PATH=".:$(__path "vmtools")" \
. vmtools.sh >/dev/null 2>&1 || {
  echo "I can't see vmtools.sh. Are vmtools installed?" >&2
  exit 1
}

clishe_init

clishe_defopt --dry-run -- "" DRY_RUN <<__HELP__
only print what should be done, do not perform anything
__HELP__
clishe_defopt --help -h -? -- "print this screen and exit" help usage

function usage() {
  cat <<-__USAGE__
	Edit vmtools configuration.

	Usage: ${clishe_scriptname} [--dry-run] [--help] [-h?]
	where

	${clishe_helplines}

	Open vmtools configuration in the editor specified by VMTOOLS_EDITOR
	with fallback to EDITOR variable (default is \`vi\`).
	__USAGE__
  exit 0
}

clishe_process_options "$@"

DRY_RUN="${DRY_RUN:-}" vmtools_edit_vmtools_config
