#!/bin/bash
#
# File:    ./vmtools-setup
# Author:  Jiří Kučera <sanczes AT gmail.com>
# Date:    2020-03-28 14:55:06 +0100
# Project: Virtual Machine Tools (vmtools)
# Brief:   Setup vmtools configuration and directories
#
# SPDX-License-Identifier: MIT
#

set -euo pipefail

# shellcheck source=/usr/local/share/clishe/clishe.sh
PATH="/usr/local/share/clishe:/usr/share/clishe${PATH:+:}${PATH}" \
. clishe.sh >/dev/null 2>&1 || {
  echo "clishe library is not installed!" >&2
  exit 1
}

PATH=".:/usr/local/share/vmtools:/usr/share/vmtools${PATH:+:}${PATH}" \
. vmtools.sh >/dev/null 2>&1 || {
  echo "I can't see vmtools.sh. Are vmtools installed?" >&2
  exit 1
}

clishe_init

clishe_defopt --dry-run -- "" DRY_RUN <<__HELP__
only print what should be done, do not perform anything
__HELP__
clishe_defopt --help -h -? -- "print this screen and exit" help usage

function usage() {
  cat <<-__USAGE__
	Setup vmtools configuration and directories.

	Usage: ${clishe_scriptname} [--dry-run] [--help] [-h?]
	where

	${clishe_helplines}

	Create an initial configuration and image storage in the user's home
	directory.
	__USAGE__
  exit 0
}

clishe_process_options "$@"

DRY_RUN="${DRY_RUN:-}" vmtools_setup
